# Generated by Django 3.0.3 on 2020-07-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_database', models.IntegerField()),
                ('kategori', models.CharField(max_length=100)),
                ('nama_kitab', models.CharField(max_length=1000)),
                ('pengarang', models.CharField(max_length=1000)),
                ('no_halaman', models.TextField()),
                ('teks_processing', models.TextField()),
            ],
        ),
    ]
