# Generated by Django 3.0.3 on 2020-07-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadkitab',
            name='konfirmasi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadkitab',
            name='username',
            field=models.CharField(default='Admin', max_length=150),
        ),
    ]
